[package]
name = "ludum_dare_54"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
bevy_common_assets = { version = "0.7.0", features = ["ron"] }
serde = "1.0.188"
